/// <reference types="google.maps" />
import { AfterViewInit, ChangeDetectionStrategy, Component, ElementRef, OnDestroy, inject, input, output, signal, viewChild } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { importLibrary } from '@googlemaps/js-api-loader';
import { TranslatePipe } from '../../../../i18n/translate.pipe';
import { GoogleMapsLoaderService } from '../../../../core/maps/google-maps-loader.service';
import { LanguageService } from '../../../../i18n/language.service';
import { ZonesService } from '../zones.service';
import { CityBoundary } from '../../../super-admin/geography/geography.models';
import { GeoJsonPolygon, IRAQ_MAP_FALLBACK, MapCenter, Zone } from '../zones.models';
import { getApiErrorMessage, isApiErrorCode } from '../../../../core/http/api-error';

@Component({ selector: 'app-zone-editor', standalone: true, imports: [FormsModule, TranslatePipe], templateUrl: './zone-editor.html', styleUrl: './zone-editor.css', changeDetection: ChangeDetectionStrategy.OnPush })
export class ZoneEditorComponent implements AfterViewInit, OnDestroy {
  private loader = inject(GoogleMapsLoaderService); private api = inject(ZonesService); private lang = inject(LanguageService);
  readonly zone = input<Zone | null>(null); readonly cityId = input.required<string>(); readonly cityBoundary = input<CityBoundary | null>(null); readonly references = input<Zone[]>([]); readonly fallbackCenter = input<MapCenter>(IRAQ_MAP_FALLBACK);
  readonly closed = output<void>(); readonly saved = output<Zone>(); readonly name = signal(''); readonly tool = signal<'drawing' | 'editing'>('drawing'); readonly saving = signal(false); readonly fieldError = signal<string | null>(null); readonly nameInvalid = signal(false); readonly mapReady = signal(false); readonly mapFailed = signal(false);
  private host = viewChild.required<ElementRef<HTMLDivElement>>('editorMap'); private search = viewChild<ElementRef<HTMLInputElement>>('searchInput'); private map: google.maps.Map | null = null; private polygon: google.maps.Polygon | null = null; private cityPolygons: google.maps.Polygon[] = []; private referencePolygons: google.maps.Polygon[] = []; private points: google.maps.LatLngLiteral[] = []; private original: GeoJsonPolygon | null = null; private listeners: google.maps.MapsEventListener[] = [];
  ngAfterViewInit() { this.name.set(this.zone()?.name ?? ''); this.original = this.zone()?.boundary ?? null; void this.init(); }
  ngOnDestroy() { this.listeners.forEach(x => x.remove()); this.polygon?.setMap(null); this.cityPolygons.forEach(x => x.setMap(null)); this.referencePolygons.forEach(x => x.setMap(null)); }
  cancel() { this.closed.emit(); } startDrawPolygon() { this.points = []; this.polygon?.setMap(null); this.polygon = null; this.tool.set('drawing'); }
  finishDrawing() { if (this.points.length < 3) { this.fieldError.set(this.lang.t('zones.needBoundary')); return; } this.render(this.points); this.tool.set('editing'); }
  startEditVertices() { if (this.polygon) { this.polygon.setEditable(true); this.tool.set('editing'); } } resetBoundary() { this.original ? this.render(this.from(this.original)) : this.startDrawPolygon(); }
  fitToZone() { if (this.zone()) this.fit([this.zone()!]); } fitToAllZones() { this.fit(this.references()); }
  private async init() { try { await this.loader.load(); const maps = await importLibrary('maps'); const c = this.fallbackCenter(); this.map = new maps.Map(this.host().nativeElement, { center: { lat: c.latitude, lng: c.longitude }, zoom: c.zoom, mapTypeControl: false, streetViewControl: false }); this.listeners.push(this.map.addListener('click', (e: google.maps.MapMouseEvent) => { if (this.tool() === 'drawing' && e.latLng) { this.points.push({ lat: e.latLng.lat(), lng: e.latLng.lng() }); this.draft(); } })); this.drawCityBoundary(); this.drawReferences(); if (this.original) { this.render(this.from(this.original)); this.tool.set('editing'); } this.mapReady.set(true); if (!this.fitCityBoundary()) this.fit(this.references()); } catch { this.mapFailed.set(true); } }
  private rings() { const b = this.cityBoundary(); return !b ? [] : b.type === 'Polygon' ? [b.coordinates] : b.coordinates; }
  private drawCityBoundary() { if (!this.map) return; this.cityPolygons = this.rings().map(r => new google.maps.Polygon({ map: this.map!, paths: r.map(x => x.map(([lng, lat]) => ({ lat, lng }))), strokeColor: '#2563eb', strokeWeight: 3, fillColor: '#2563eb', fillOpacity: .08, clickable: false })); }
  private drawReferences() { if (!this.map) return; this.referencePolygons = this.references().filter(zone => zone.id !== this.zone()?.id && zone.status !== 'ARCHIVED').map(zone => new google.maps.Polygon({ map: this.map!, paths: zone.boundary.coordinates.map(ring => ring.map(([lng, lat]) => ({ lat, lng }))), strokeColor: '#64748b', strokeWeight: 2, fillColor: '#64748b', fillOpacity: .18, clickable: false, zIndex: 2 })); }
  private fitCityBoundary() { if (!this.map || !this.cityPolygons.length) return false; const b = new google.maps.LatLngBounds(); for (const rs of this.rings()) for (const r of rs) for (const [lng, lat] of r) b.extend({ lat, lng }); this.map.fitBounds(b, 56); return true; }
  private draft() { if (!this.map) return; if (!this.polygon) this.polygon = new google.maps.Polygon({ map: this.map, fillColor: '#FE5104', fillOpacity: .2, strokeColor: '#FE5104', strokeWeight: 3 }); this.polygon.setPath(this.points); }
  private render(points: google.maps.LatLngLiteral[]) { if (!this.map) return; this.polygon?.setMap(null); this.polygon = new google.maps.Polygon({ map: this.map, paths: points, fillColor: '#FE5104', fillOpacity: .2, strokeColor: '#FE5104', strokeWeight: 3, editable: true }); }
  private from(b: GeoJsonPolygon) { return (b.coordinates[0] ?? []).slice(0, -1).map(([lng, lat]) => ({ lat, lng })); }
  private fit(zones: readonly Zone[]) { if (!this.map || !zones.length) return; const b = new google.maps.LatLngBounds(); for (const z of zones) for (const r of z.boundary.coordinates) for (const [lng, lat] of r) b.extend({ lat, lng }); this.map.fitBounds(b, 72); }
  private read(): GeoJsonPolygon | null { if (!this.polygon || this.tool() === 'drawing') return null; const p = this.polygon.getPath(); if (p.getLength() < 3) return null; const r = Array.from({ length: p.getLength() }, (_, i) => { const x = p.getAt(i)!; return [x.lng(), x.lat()]; }); r.push([...r[0]!]); return { type: 'Polygon', coordinates: [r] }; }
  async save() { if (this.tool() === 'drawing' && this.points.length >= 3) this.finishDrawing(); const boundary = this.read(), name = this.name().trim(); this.nameInvalid.set(!name); if (!name || !boundary) { this.fieldError.set(this.lang.t(!name ? 'zones.nameRequired' : 'zones.needBoundary')); return; } this.saving.set(true); this.fieldError.set(null); try { const z = this.zone(); this.saved.emit(z ? await this.api.update(this.cityId(), z.id, { name, boundary }) : await this.api.create({ cityId: this.cityId(), name, boundary })); } catch (error) { this.fieldError.set(isApiErrorCode(error, 'ZONE_BOUNDARY_OVERLAP') ? this.lang.t('zones.overlapError') : getApiErrorMessage(error, this.lang.t('common.unexpectedError'))); } finally { this.saving.set(false); } }
}
