/// <reference types="google.maps" />
import { AfterViewInit, ChangeDetectionStrategy, Component, ElementRef, OnDestroy, effect, inject, input, output, signal, viewChild } from '@angular/core';
import { importLibrary } from '@googlemaps/js-api-loader';
import { TranslatePipe } from '../../../../i18n/translate.pipe';
import { GoogleMapsLoaderService } from '../../../../core/maps/google-maps-loader.service';
import { CityBoundary } from '../../../super-admin/geography/geography.models';
import { IRAQ_MAP_FALLBACK, MapCenter, Zone } from '../zones.models';
@Component({selector:'app-zone-map',standalone:true,imports:[TranslatePipe],templateUrl:'./zone-map.html',styleUrl:'./zone-map.css',changeDetection:ChangeDetectionStrategy.OnPush})
export class ZoneMapComponent implements AfterViewInit,OnDestroy {
 private loader=inject(GoogleMapsLoaderService); readonly zones=input<Zone[]>([]); readonly cityBoundary=input<CityBoundary|null>(null); readonly selectedId=input<string|null>(null); readonly previewZone=input<Zone|null>(null); readonly loading=input(false); readonly error=input(false); readonly fallbackCenter=input<MapCenter>(IRAQ_MAP_FALLBACK); readonly selectZone=output<string>(); readonly mapReady=signal(false); readonly mapFailed=signal(false); private host=viewChild.required<ElementRef<HTMLDivElement>>('mapHost'); private map:google.maps.Map|null=null; private zonePolygons=new Map<string,google.maps.Polygon>(); private cityPolygons:google.maps.Polygon[]=[];
 constructor(){effect(()=>{this.zones();this.cityBoundary();this.selectedId();this.previewZone();this.sync();});}
 ngAfterViewInit(){void this.init();} ngOnDestroy(){this.zonePolygons.forEach(p=>p.setMap(null));this.cityPolygons.forEach(p=>p.setMap(null));}
 private async init(){try{await this.loader.load();const maps=await importLibrary('maps');const c=this.fallbackCenter();this.map=new maps.Map(this.host().nativeElement,{center:{lat:c.latitude,lng:c.longitude},zoom:c.zoom,mapTypeControl:false,streetViewControl:false,fullscreenControl:true,clickableIcons:false,gestureHandling:'greedy'});this.mapReady.set(true);this.sync();this.fitCity();}catch{this.mapFailed.set(true);}}
 private rings(){const b=this.cityBoundary();return !b?[]:b.type==='Polygon'?[b.coordinates]:b.coordinates;}
 private sync(){if(!this.map)return;this.cityPolygons.forEach(p=>p.setMap(null));this.cityPolygons=this.rings().map(r=>new google.maps.Polygon({map:this.map!,paths:r.map(x=>x.map(([lng,lat])=>({lat,lng}))),strokeColor:'#2563eb',strokeWeight:3,fillColor:'#2563eb',fillOpacity:.08,clickable:false,zIndex:1}));const ids=new Set(this.zones().map(z=>z.id));for(const [id,p] of this.zonePolygons)if(!ids.has(id)){p.setMap(null);this.zonePolygons.delete(id);}for(const z of this.zones()){const paths=z.boundary.coordinates.map(r=>r.map(([lng,lat])=>({lat,lng})));let p=this.zonePolygons.get(z.id);if(!p){p=new google.maps.Polygon({map:this.map,clickable:true,zIndex:2});p.addListener('click',()=>this.selectZone.emit(z.id));this.zonePolygons.set(z.id,p);}p.setPaths(paths);p.setOptions({fillColor:z.status==='ACTIVE'?'#059669':'#6b7280',fillOpacity:.22,strokeColor:this.selectedId()===z.id?'#FE5104':'#64748b',strokeWeight:this.selectedId()===z.id?4:2});}}
 private fitCity(){if(!this.map||!this.rings().length)return;const b=new google.maps.LatLngBounds();for(const rs of this.rings())for(const r of rs)for(const [lng,lat] of r)b.extend({lat,lng});this.map.fitBounds(b,56);}
}
